const SMALL_TIMEOUT = 2*1000;
const MEDIUM_TIMEOUT = 5*1000;
const LARGE_TIMEOUT = 10*1000;

exports.SMALL_TIMEOUT = SMALL_TIMEOUT;
exports.MEDIUM_TIMEOUT = MEDIUM_TIMEOUT;
exports.LARGE_TIMEOUT = LARGE_TIMEOUT;